### PR TITLE
fix tf_prefix leading slash issue

### PR DESCRIPTION
**Pull request by jihoonl**
#13

### CODE REVIEW

**Comment by jack-oquin** [comment]
I see how this gets rid of the initial '/', but what happens if ``tf_prefix`` is actually defined?

**Comment by piyushk** [comment]
I agree with @joq. The tf_prefix parameter should be removed from the file that doesn''t support it. In case someone is already using the feature in Indigo, I want that launch file to do a hard fail instead of failing without an error. We've already established that we need to fix this issue in Indigo.

@jihoonl Could you remove the tf_prefix param from the file that doesn't support it?

**Comment by jihoonl** [comment]
Removed.

**Comment by jack-oquin** [comment]
It should still be possible to make ``tf_prefix`` work, by testing for a definition in the code. That seems better.

**Comment by jihoonl** [comment]
I have merged `tf_prefix` version and original version. It seems to work for all purpose.

@jack-oquin What do you mean by `by testing for a definition in the code`?

**Comment by jack-oquin** [comment]
The driver would ``searchParam()``, and if it finds ``tf_prefix`` defined anywhere in or above the driver's namespace, it would build the ``Header.frame_id`` using the prefix, a '/' character, followed by the ``rgb_frame_id`` or ``depth_frame_id``.

**Comment by piyushk** [comment]
@jack-oquin `tf_prefix` in code was deprecated in Hydro through most of ROS, and based on past experience adding that parameter in each individual piece of code also introduces problems since it may change the behavior of other legacy code in unexpected ways. Since there is no accepted convention, I prefer the current solution since it matches openni2_launch as well.

**Comment by piyushk** [comment]
@jihoonl Somethings off in this PR. Given your two latest commits there were no changes. Could you take a look and get back to me?

**Comment by jihoonl** [comment]
The last two commits were to merge `freenect.launch` and `freenect_tf_prefix.launch`

It seemed like `freenect_tf_prefix.launch` can be used for all purposes(with or without tf_prefix). So I removed no tf_prefix version and renamed freenect_tf_prefix.launch to freenect.launch

**Comment by piyushk** [comment]
The files changed tab only shows a whitespace change: 
https://github.com/ros-drivers/freenect_stack/pull/15/files

Since freenect_tf_prefix launch file was the original freenect launch file anyway, it doesn't surprise me that there were no changes. However, it's not clear to me if your problem got solved or if there is anything new to release.

**Comment by jihoonl** [comment]
Ah ha...it is weird. :( I will get back to the issue after testing.

**Comment by jihoonl** [comment]
Ah...my bad. the current release version works fine without warning. I was getting the leading slash warning when I subscribed to `depth_registered/points` with depth_registration flag off..

**Pull request merged**
