### PR TITLE
Add Travis CI config

### PR DESCRIPTION
**Pull request by 130s**
If this looks good, then anybody with admin rights please activate Travis CI for this repo. It should be done with a single click, somewhere like https://travis-ci.org/profile/ros-drivers.

### CODE REVIEW

**Comment by piyushk** [comment]
@130s Will this now automatically show up on the entry page for the stack? or does something need to be added to the readme file. If it does, could you add that this PR?

**Comment by jack-oquin** [comment]
Thanks for taking the lead on this, Isaac.

I am not sure exactly what is involved or how it all works, am very supportive of the concept.

**Comment by 130s** [comment]
@piyushk sorry, I'm not sure what you mean. Can you point me to any example?

**Comment by piyushk** [comment]
Here's an example: The following change in the README.md file display a build button on the main github page:
https://raw.githubusercontent.com/segwayrmp/libsegwayrmp/master/README.md
https://github.com/segwayrmp/libsegwayrmp

**Comment by 130s** [comment]
Ah, I see. I didn't know TravisCI provides such an image.
Now added and squashed.

**Comment by jack-oquin** [comment]
Thanks for doing this, Isaac!

Do we still need to do the admin part mentioned in your first comment?

**Comment by 130s** [comment]
> Do we still need to do the admin part mentioned in your first comment?

Looks like yes. Thank you in advance.

**Comment by jack-oquin** [comment]
It looks like the ``ros-drivers`` organization is already authorized for Travis, but when I click on the build status for *this* repository, it says it's not active.

Any idea what's missing?

**Comment by jack-oquin** [comment]
Maybe it just needs a new push that Travis can see.

**Comment by jack-oquin** [comment]
I just pushed a trivial change. No immediate effect that I can see.

**Comment by jack-oquin** [comment]
I think it's working now.

**Pull request merged**
